name: OS Docker INIT
  
on:
  schedule:
    - cron:  '0 0 * * MON'
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  Build_For_Centos:
    name: OS Docker Centos INIT
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v5
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - 
        name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: xrsec
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Centos
          push: true
          tags: |
            xrsec/osinit:centos
            ghcr.io/xrsec/osinit:centos
          cache-from: type=registry,ref=xrsec/osinit:centos.cache
          cache-to: type=registry,ref=xrsec/osinit:centos.cache,mode=max


  Build_For_Ubuntu:
    name: OS Docker Ubuntu INIT
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v5
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - 
        name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: xrsec
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Ubuntu
          push: true
          tags: |
            xrsec/osinit:ubuntu
            ghcr.io/xrsec/osinit:ubuntu
          cache-from: type=registry,ref=xrsec/osinit:ubuntu.cache
          cache-to: type=registry,ref=xrsec/osinit:ubuntu.cache,mode=max

  Update_Docker_Hub_Description:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v5
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: xrsec
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: xrsec/osinit