name: OS Docker INIT
  
on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  Build For Centos:
    name: OS Docker Centos INIT
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: xrsec
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Centos
          push: true
          tags: |
            xrsec/osinit:centos
          cache-from: type=registry,ref=xrsec/osinit:centos.cache
          cache-to: type=registry,ref=xrsec/osinit:centos.cache,mode=max

  Build For Ubuntu:
    name: OS Docker Ubuntu INIT
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: xrsec
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: Dockerfiles/Ubuntu
          push: true
          tags: |
            xrsec/osinit:ubuntu
          cache-from: type=registry,ref=xrsec/osinit:ubuntu.cache
          cache-to: type=registry,ref=xrsec/osinit:ubuntu.cache,mode=max

  Update_Docker_Hub_Description:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: xrsec
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: xrsec/osinit
